# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8V5yM3RAC9CrOHWlcQPZ1eIyU0P3Aq0
"""

a = int(input("Primer número: "))
b = int(input("Segundo número: "))

if a == 0 or b == 0:
    print("El resultado es 0")
else:
    print("Resultado:", a * b)